### ISSUE TITLE
Delims

### ISSUE THREAD

**Issue by elizabethshirley** [jsks/parmap#1]
You likely want to use standard function isspace() (located in ctype.h) instead of defined isdelim(). Most implementations of isspace() test with one or two assembly instructions, instead of looping, additionally covers more white-space characters, including \v \r \f

**Comment by jsks** [comment]
Great point. I initially wanted to be able to use the same delimiter checking function for both the defaults and any user specified delimiters, but there's no reason I can't just use isspace in case the user hasn't specified anything.
